config/routes.rb
Missions::Application.routes.draw do

  

  resources :links
  match "faq" => "questions#index"
  resources :questions

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "contact/thank-you" => 'contacts#thanks', as: "contacted"
  match "contact" => 'contacts#new', as: "contact"
  resources :contacts

  resources :churches

  resources :categories

  mount RedactorRails::Engine => '/redactor_rails'

  match "posts/category" => "posts#category"
  resources :posts

  resources :blogs

  get "pages/home"

  match "about" => "pages#about", as: "pages_about"
  get "pages/about"

  match "mission" => "pages#mission", as: "pages_mission"
  get "pages/mission"

  match "support" => "pages#support", as: "pages_support"
  get "pages/support"

  root :to => 'pages#home'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :name

  has_many :posts

  validates_presence_of :name
  validates_uniqueness_of :name

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    @posts = @blog.posts.order("published_on desc").where('status = ? AND published_on <= ?', "Published", Date.today).page(params[:page]).per(4)
    @blog_list = Blog.order("name asc")
    @latest_posts = Post.order("published_on desc").limit(4)
    @side_posts = Post.where('status = ? AND published_on <= ?', "Published", Date.today).order("published_on desc").limit(10)
    @all_categories = Category.order("name ASC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.name %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<%= provide(:title, "Blog") %>		
<%= render "partials/hdr" %>		

<div class="pg-container bg-white">
	
	<div class="container">
		<div id="secondary-pg-title">
			<div class="row">
				<div class="span1">
					<%= image_tag("uk-map.jpg", size: "66x100") %>
				</div>
				<div class="span11">
					<h2 class="sec-title"><%= "Latest Updates from " + "#{@blog.name}" %></h2>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div id="posts-container">
			<div class="row">
				<div class="span9">
					<% if @blog.posts.blank? %>
						<h4>Sorry, <%= @blog.name %> currently has no viewable posts.
					<% else %>
					<% for post in @posts %>
						<div class="post">
							<div class="row">
								<div class="span1">&nbsp;
								</div>
								<div class="span8">
									<div class="post-main">
										<h2 class="blog-post-title"><%= link_to post.title, post %></h2>
										<em><p class="blog-detail">Posted by <%= link_to @blog.name, blog_path %> on <%= post.published_on.strftime("%B %-d, %Y") %> |
										Category:
										<%= post.categories.collect { |cat| cat.name }.join(", ") %>		
										
										</p></em>
										<%= sanitize post.body %>
										
									</div>
								</div>
							</div>
						</div>
					<% end %>

					<% end %>	

					<%= paginate @posts %>		
							
												
				</div>
				<div class="span3">
					<div id="search-container">
						<%= form_tag posts_path, method: "get" do %>
							<div class="input-append">
								<%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search..." %>
								<%= submit_tag "Search", name: nil, class: "btn" %>				
							</div>
						<% end %>		
					</div>
					<div id="recent-posts">
						<h4>Recent Posts</h4>
						<ul>
						<% for post in @side_posts %>
							<li><%= link_to post.title, post %></li>
						<% end %>
						<ul>
					</div>
					<div id="categories">
						<h4>Categories</h4>
						<ul>
							<% @all_categories.each do |cat| %>
								<li><%= link_to(cat.name, { action: "category", controller: "posts", id: cat.id }) %></li>
							<% end %>		
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render "partials/ftr" %>		