config/routes.rb
Missions::Application.routes.draw do

  

  resources :links
  match "faq" => "questions#index"
  resources :questions

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "contact/thank-you" => 'contacts#thanks', as: "contacted"
  match "contact" => 'contacts#new', as: "contact"
  resources :contacts

  resources :churches

  resources :categories

  mount RedactorRails::Engine => '/redactor_rails'

  match "posts/category" => "posts#category"
  resources :posts

  resources :blogs

  get "pages/home"

  match "about" => "pages#about", as: "pages_about"
  get "pages/about"

  match "mission" => "pages#mission", as: "pages_mission"
  get "pages/mission"

  match "support" => "pages#support", as: "pages_support"
  get "pages/support"

  root :to => 'pages#home'

end

app/models/church.rb
class Church < ActiveRecord::Base
  attr_accessible :city, :link, :name, :state

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :link
  validates_uniqueness_of :link

end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController
  # GET /churches
  # GET /churches.json
  def index
    @churches = Church.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @churches }
    end
  end

  # GET /churches/1
  # GET /churches/1.json
  def show
    @church = Church.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @church }
    end
  end

  # GET /churches/new
  # GET /churches/new.json
  def new
    @church = Church.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @church }
    end
  end

  # GET /churches/1/edit
  def edit
    @church = Church.find(params[:id])
  end

  # POST /churches
  # POST /churches.json
  def create
    @church = Church.new(params[:church])

    respond_to do |format|
      if @church.save
        format.html { redirect_to @church, notice: 'Church was successfully created.' }
        format.json { render json: @church, status: :created, location: @church }
      else
        format.html { render action: "new" }
        format.json { render json: @church.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /churches/1
  # PUT /churches/1.json
  def update
    @church = Church.find(params[:id])

    respond_to do |format|
      if @church.update_attributes(params[:church])
        format.html { redirect_to @church, notice: 'Church was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @church.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /churches/1
  # DELETE /churches/1.json
  def destroy
    @church = Church.find(params[:id])
    @church.destroy

    respond_to do |format|
      format.html { redirect_to churches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/views/churches/_form.html.erb
<%= form_for(@church) do |f| %>
  <% if @church.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@church.errors.count, "error") %> prohibited this church from being saved:</h2>

      <ul>
      <% @church.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/churches/edit.html.erb
<h1>Editing church</h1>

<%= render 'form' %>

<%= link_to 'Show', @church %> |
<%= link_to 'Back', churches_path %>

app/views/churches/index.html.erb
<h1>Listing churches</h1>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @churches.each do |church| %>
  <tr>
    <td><%= church.name %></td>
    <td><%= church.city %></td>
    <td><%= church.state %></td>
    <td><%= church.link %></td>
    <td><%= link_to 'Show', church %></td>
    <td><%= link_to 'Edit', edit_church_path(church) %></td>
    <td><%= link_to 'Destroy', church, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Church', new_church_path %>

app/views/churches/new.html.erb
<h1>New church</h1>

<%= render 'form' %>

<%= link_to 'Back', churches_path %>

app/views/churches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @church.name %>
</p>

<p>
  <b>City:</b>
  <%= @church.city %>
</p>

<p>
  <b>State:</b>
  <%= @church.state %>
</p>

<p>
  <b>Link:</b>
  <%= @church.link %>
</p>


<%= link_to 'Edit', edit_church_path(@church) %> |
<%= link_to 'Back', churches_path %>