config/routes.rb
Missions::Application.routes.draw do

  

  resources :links
  match "faq" => "questions#index"
  resources :questions

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "contact/thank-you" => 'contacts#thanks', as: "contacted"
  match "contact" => 'contacts#new', as: "contact"
  resources :contacts

  resources :churches

  resources :categories

  mount RedactorRails::Engine => '/redactor_rails'

  match "posts/category" => "posts#category"
  resources :posts

  resources :blogs

  get "pages/home"

  match "about" => "pages#about", as: "pages_about"
  get "pages/about"

  match "mission" => "pages#mission", as: "pages_mission"
  get "pages/mission"

  match "support" => "pages#support", as: "pages_support"
  get "pages/support"

  root :to => 'pages#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :name

  has_many :posts

  validates_presence_of :name
  validates_uniqueness_of :name

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  attr_accessible :category_id, :post_id

  belongs_to :post
  belongs_to :category
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :categorizations
  has_many :posts, through: :categorizations

  validates_presence_of :name
  validates_uniqueness_of :name

end

app/models/church.rb
class Church < ActiveRecord::Base
  attr_accessible :city, :link, :name, :state

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :link
  validates_uniqueness_of :link

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :church, :email, :first_name, :last_name, :message, :phone

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :message, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }


end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :link, :name

  validates :name, presence: true, uniqueness: true
  validates :link, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :blog_id, :body, :published_on, :status, :title, :category_ids
  
  belongs_to :blog

  has_many :categorizations
  has_many :categories, through: :categorizations
  accepts_nested_attributes_for :categorizations


  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :body
  validates_presence_of :blog
  validates_presence_of :status

  extend FriendlyId
  friendly_id :title, use: :slugged

  def self.search(search)
  	if search
  		find(:all, conditions: ['title || body LIKE ?', "%#{search}%"], conditions: ['status = ? AND published_on <= ?', "Published", Date.today], order: "published_on DESC")
  	else
  		find(:all, conditions: ['status = ? AND published_on <= ?', "Published", Date.today], order: "published_on DESC")
  	end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :position, :question

  validates_presence_of :question
  validates_presence_of :answer
  validates_presence_of :position

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    @posts = @blog.posts.order("published_on desc").where('status = ? AND published_on <= ?', "Published", Date.today).page(params[:page]).per(4)
    @blog_list = Blog.order("name asc")
    @latest_posts = Post.order("published_on desc").limit(4)
    @side_posts = Post.where('status = ? AND published_on <= ?', "Published", Date.today).order("published_on desc").limit(10)
    @all_categories = Category.order("name ASC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def index
		@blog_list = Blog.order("name asc")
    	@latest_posts = Post.order("published_on desc").limit(4)
    	@churches = Church.order("name asc")
    	@links = Link.order("name asc")
    	@blogs = Blog.order("name asc")
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %> - O, the Places You'll Go</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<body>

<%= yield %>

</html>

app/views/pages/about.html.erb
<%= provide(:title, "About Us") %>		
<%= render "partials/hdr" %>

<div class="pg-container bg-white">
	
	<div class="container">
		<div id="secondary-pg-title">
			<div class="row">
				<div class="span1">
					<%= image_tag("uk-map.jpg", :size => "66x100") %>
				</div>
				<div class="span11">
					<h2 class="sec-title">A little more of our story...</h2>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div id="about-pg">
			<div class="row">
				<div class="span8">
					<div id="about-content">
					<h3 class="about-page">Unlikely Missionaries</h3>
						<p>We are unlikely missionaries. But as we were approaching an empty nest, God began to take us on a journey of adventure and even deeper dependence on 	him. In January 2012, Bing badly broke his knee, spending several months unable to walk while recoving.</p>
						<p>With plenty of time to think and pray, and an 'accidental encounter' with a missionary during that time, we found our hearts being curiously drawn to 	cross-cultural ministry for the first time ever. After eight months of process with Mission To the World (MTW), we find ourselves fully approved and 	headed to the mission field.</p>
						<p>We have three fabulous, somewhat-grown children, who will not be moving to London with us. <strong>Will</strong>, age 24, graduated from the University of Tennessee this past spring with a degree in Political Science and minor in German. <strong>Logan</strong>, age 23, graduated from New 	College Franklin, a small classical college, this past spring, and married his bride, Marley, shortly thereafter. We also have <strong>Kate</strong>, age 19, who is a sophomore nursing student	at the University of Pennsylvania. Will and Kate have both spent time working in outreach ministry in London in the same part of the city in which we will most likely live, and Logan can give a great literary-historical guided tour of London. So as you can see, London is a place much-loved by our family.</p>
	
						<p>Would you consider partnering with us?</p>
	
						<p><%= link_to "Learn More", pages_support_path, :class => "btn btn-small" %></p>
					</div>
					<br>
					<div id="partnering-list">
						<h4>Parterning Churches:</h4>
						<ul>
							<% for church in @churches %>
							<li><%= link_to "#{church.name + " - " + church.city + ", " + church.state}", church.link, :target => "_blank" %></li>
							<% end %>
						</ul>
					</div>
				</div>
				<div class="span4">
					<div id="about-img-container">
						<%= image_tag "bing-stacy-2.jpg" %>	
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render "partials/ftr" %>	

app/views/pages/home.html.erb
<%= provide(:title, "Home") %>		
<%= render "partials/hdr" %>		
<div class="pg-container bg-white">
<div id="rev-top">
	<div class="container">
		<div class="row">
			
			<div class="span4">
				<div class="map-container">
					<%= image_tag "uk-map.jpg" %>		
				</div>
				<div class="below-map-container">
					
					<p>Please go to <%= link_to "www.mtw.org", "http://www.mtw.org" %> and click on "DONATE NOW".</p>

					<p>You can also mail a check to:</p>
			<address>
				<strong>Mission to the World</strong><br>
				P.O. Box 116284<br>
				Atlanta, GA 30368-6284<br>
				<strong>Reference Support Account #11877</strong>
			</address>
				</div>
			</div>
			<div class="span8">
				<h1 class="title-sub">O, the places you'll go!</h1>
				
				<h3 class="call-text">Would you consider changing one of the Union Jacks to a Map Pointer by committing to partner with us with a $100/month gift for the next 5 years?</h3>

				<%= image_tag "union-jack_800.jpg" %>

			<!--
			<div class="span4">
				<%= image_tag "uk-map.jpg" %>		
			</div>
			<div class="span8">
				<h1>O, the places you'll go!</h1>
				

				<%= image_tag "union-jack_800.jpg" %>
				<!-- REGULAR HOME CONTENT BELOW -->
				<!-- 
				<blockquote>
					"We want to officially extend an invitation to serve in the MTW's ministry in the United Kingdom...we do believe you are called to be a part of MTW's work in this country. We understand that you are committing to stay on the field for long term...We are anticipating your ministry would help facilitate church planting in London."
				</blockquote>	
				<p>After serving as a PCA pastor and raising children for the last 20+ years, we are unlikely missionaries. But as we approached an empty nest, God began to take us on a journey of adventure and even deeper dependence on Him.</p>
				<p><%= link_to "Read more of our story...", pages_about_path %></p>
				<p>To give you a better idea of our current support level and where we need to get to, we have generated a <%= link_to "visual representation", "/where-we-stand.pdf", target: "_blank" %>.</p>
			-->

			</div>
		</div>
	</div>
</div>


<div class="container" id="boxes">
	<div class="row">
		<div class="span4">
			<h4><i class="icon-screenshot icon-heading red"></i>About Us</h4>
			<p class="padr20"><%= image_tag "bing_stacy_11-15.jpg" %></p>		
			<p><%= link_to "Read our story", pages_about_path, class: "btn btn-small" %></p>
			
		</div>
		<div class="span4">
			<h4><i class="icon-screenshot icon-heading red"></i>The Vision</h4>
			<p class="padr20">The call to the United Kingdom is to work with existing church plants undertaken by partnerministries in London. We will begin our ministry working with church planters in various parts of London, most of them very diverse ethnically.</p>
			<p><%= link_to "Read More", pages_mission_path, class: "btn btn-small" %></p>
		</div>
		<div class="span4">
			<h4><i class="icon-screenshot icon-heading red"></i>The Need</h4>
			<p>In the last 50 years, the geographic center of Christianity has moved South and East. <em class="red">In the UK and on the European continent, what we historically call "Christendom," the home of vital and missional Christianity for centuries, Christianity is dying.</em> In the UK the evangelical population amounts to...</p>
			<p><%= link_to "Read More", pages_mission_path, class: "btn btn-small" %></p>
		</div>
		
	</div>
</div>
<%= render "partials/ftr" %>		

app/views/pages/links.html.erb
<h1>Pages#links</h1>
<p>Find me in app/views/pages/links.html.erb</p>

app/views/pages/mission.html.erb
<%= provide(:title, "Our Mission") %>		
<%= render "partials/hdr" %>
<div class="pg-container bg-white">

	<div class="container">
		<div id="secondary-pg-title">
			<div class="row">
				<div class="span1">
					<%= image_tag("uk-map.jpg", size: "66x100") %>
				</div>
				<div class="span11">
					<h2 class="sec-title">About Our Mission</h2>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div id="mission-pg">
			<div class="row">
				<div class="span7">
					<h3 class="about-page">The Vision</h3>
					<p>The call to London is to work with existing church planters and partner ministries. We will begin our ministry in various parts of the city, many of them diverse ethnically. We will begin helping to mentor, train, and educate these church planters as well as assisting our national partners in recruiting, training new church planters for London.</p>
					<h3 class="about-page">The Need</h3>
					<p>In the last 50 years, the geographic center of Christianity has moved South and East. <em class="red">In the UK and on the European continent, what we historically call "Christendom," the home of vital and missional Christianity for centuries, Christianity is dying.</em> In the UK, the evangelical population amounts to about 2% of the entire population, demonstrating the dire need for evangelism through church planting.</p>
					<h3 class="about-page">Our Goals</h3>
					<h5 class="red goal-title">Goal One</h5>
					
					<p>Develop mentoring relationships with local church planters, helping them to minister effectively to their neighborhoods, seeing new converts and participating in life-giving ministries of mercy, teaching, and evangelism.</p>
					<h5 class="red goal-title">Goal Two</h5>
					<p>Assist in identifying men to lead future church plants. We believe this is a work of generations, so we pray also that we will be able to train and work with our successors.</p>
				</div>
				<div class="span4 offset1">
					<div id="mission-side-container">
						<h4 class="about-page">Partner with Us</h4>
						<p>This London project is an opportunity for all to partner in the work of the kingdom, a chance to invest in spreading the gospel to "the nations" that congregate in London.</p>
						<p>Would you consider partnering with us?</p>
						<p><%= link_to "Learn More", pages_support_path, class: "btn btn-small" %></p>
						<div id="mission-pg-church-list">
						<h4 class="about-page">Partnering Churches</h4>
							<ul>
								<% for church in @churches %>
							<li><%= link_to "#{church.name + " - " + church.city + ", " + church.state}", church.link, target: "_blank" %></li>
							<% end %>		
							</ul>
						</div>
						
						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render "partials/ftr" %>				

app/views/pages/missions.html.erb
<h1>Pages#missions</h1>
<p>Find me in app/views/pages/missions.html.erb</p>

app/views/pages/support.html.erb
<%= provide(:title, "Support") %>		
<%= render "partials/hdr" %>
<div class="pg-container bg-white">
	
	
	<div class="container">
		<div id="secondary-pg-title">
			<div class="row">
				<div class="span1">
					<%= image_tag("uk-map.jpg", size: "66x100") %>
				</div>
				<div class="span11">
					<h2 class="sec-title">How can you partner with us?</h2>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div id="mtw">
			<div class="row">
				<div class="span5">
					<%= image_tag "mtw-bw.jpg" %>
				</div>
				<div class="span6 offset1 mtw-text-pad">
					<blockquote class="red">"MTW believes that the Church is God's 	instrument to complete the missionary task. Ours 	approach is to advance movements of the gospel 	through the planting of self-propogating, self-	supporting, and self-governing churches, which 	live out a dynamic Reformed and covenantal faith 	through trained and empowered leadership."</blockquote>
				</div>
			</div>
		</div>
		<div id="support-text">
			<div class="row">
				<div class="span6">

			<p>This London project is an opportunity for all to partner in the work of the kingdom, a chance to invest in spreading the gospel to "the nations" that congregate in London.</p>
			<p>We have significant one-time and ongoing financial needs, but we know that God has gone before us and raised a team of partners. Are you one of those partners?</p>
			
			<p>If so, please go to <%= link_to "www.mtw.org", "http://mtw.org", target: "_blank" %> and click on "DONATE NOW".</p>
			<p>You can also mail a check to:</p>
			<address>
				<strong>Mission to the World</strong><br>
				P.O. Box 116284<br>
				Atlanta, GA 30368-6284<br>
				<strong>Reference Support Account #11877</strong>
			</address>
			
				</div>
				<div class="span6">
					<%= image_tag "post-picture-kids.jpg" %>	


				</div>

			</div>

			<p>You can also click on the image below to print off an e-giving card.</p>

			<div class="row">
				<div class="span6">
					<h4>E-giving Card</h4>
					<%= link_to image_tag("mtw-eginving-card.jpg"), "/assets/davis-eft-form.jpg", target: "_blank" %>
				</div>
				<div class="span6">
					&nbsp;	
				</div>
			</div>		
		</div>
	</div>
</div>	
<%= render "partials/ftr" %>			

app/views/partials/_ftr.html.erb
<div class="pg-container dark">
	<div class="container" id="home-bottom">
		<div class="row">
			<div class="span3">
				<h4 class="white"><i class="icon-screenshot icon-heading red"></i>Recent Updates</h4>
				<% for post in @latest_posts %>
					<h5 class="hm-post-title"><%= link_to post.title, post %></h5>
					<small class="post-detail">Posted by <%= link_to post.blog.name, post.blog %> on <%= post.created_at.strftime("%b %-d") %></small>
				<% end %>
			</div>
			
			<div class="span5">
				<h4 class="white"><i class="icon-screenshot icon-heading red"></i>Partner With Us</h4>
				<p class="padr20 ddd">This London project is an opportunity for us all to partner in the work of the kingdom, a chance to invest in the spreading of the gospel to "the nations" that congregate in London.</p>
				<p><%= link_to "Learn More", pages_support_path, class: "btn btn-small" %></p>
			</div>
			<div class="span4">
				<h4 class="white"><i class="icon-envelope icon-heading red"></i>Join Our Mailing List</h4>
				

<!-- Begin MailChimp Signup Form 
<link href="http://cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style> -->
<div id="mc_embed_signup">
<form action="http://facebook.us5.list-manage.com/subscribe/post?u=61ba4c92ba9f53d420316b8fd&amp;id=ea207340d4" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	<label for="mce-EMAIL"></label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
	<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-small"></div>
</form>
</div>

<!--End mc_embed_signup-->

<!--End mc_embed_signup-->
			</div>
		</div>
	</div>
</div>
<div class="pg-container black">
	<div class="container ft-container">
		<p class="footer-text">Mission To the World - Presbyterian Church In America</p>
	</div>
</div>

app/views/partials/_hdr.html.erb
<div class="pg-container">
	<header>
		<div class="navbar navbar-inverse">
			<div class="navbar-inner">
				<div class="container hdr-pad">
					<%= link_to "Bing & Stacy Davis...missionaries to London", root_path, :class => "brand" %>		
					<div>
						<ul class="nav pull-right">
							<li><%= link_to "About", pages_about_path %></li>
							<li><%= link_to "FAQ", questions_path %></li>
							<li><%= link_to "Support", pages_support_path %></li>
							<li><%= link_to "Our Mission", pages_mission_path %></li>
							<li><%= link_to "Links", links_path %></li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Blogs <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<% for blog in @blog_list %>
										<li><%= link_to blog.name, blog %></li>
									<% end %>
								</ul>
							</li>
							<li><%= link_to "Contact", contact_path %></li>
						</ul>
					</div>
				</div>		
			</div>
		</div>
	<header>
</div>